name: datadriven-vad
channels:
  - defaults
dependencies:
  - pip:
    - numpy
    - pandas
    - beautifulsoup4
    - requests
    - rVADfast
    - re
    - SoundFile
    - loguru
    - h5py
    - scipy
    - torch
    - sed_eval
    - pytorch_ignite
    - tqdm
    - tabulate
    - six
    - fire
    - librosa
    - ignite
    - scikit_learn
    - typing
    - PyYAML
    - numba
    - pypeln
  
